version: "3.9"
services:
  ngnix:
    container_name: my-ngnix
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 8001:80
    restart: always
    volumes:
      # - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      # - ./frontend/foody/build:/usr/share/nginx/html
    depends_on:
      - backend

  # mongodb:
  #   image: mongo:6
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: secret
  #     MONGO_INITDB_DATABASE: foody
  #   container_name: mongodb
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodb_data:/data/db

  backend:
    restart: unless-stopped
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app:/node_modules
    env_file:
      - ./backend/config.env
    # depends_on:
    #   - mongodb

  # frontend:
  #   build: ./frontend/foody
  #   ports:
  #     - "3001:3001"
  #   volumes:
  #     - ./frontend/src:/app/src
  #   stdin_open: true
  #   tty: true
  #   depends_on:
  #     - backend

volumes:
  mongodb_data:
